#!/bin/bash

set -e

ceph mgr module disable dashboard
clear-log-and-pyc

# By setting the dashboard to a static port
# you don't have to rerun 'npm start'
ceph config set mgr mgr/dashboard/x/server_port 8383

sleep 5
ceph mgr module enable dashboard --force

# Only the first time you have to wait 10s if it's created it won't change
# But it will prevent to target 'null'
sleep 10
set-proxy
